name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the app are you running?
      options:
        - 0.0.1 (Current)
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you experiencing the issue on?
      options:
        - Android
        - iOS
        - Both
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using? (e.g. iPhone 13, Samsung Galaxy S21)
      placeholder: iPhone 13 Pro
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What OS version is your device running? (e.g. iOS 15.4, Android 12)
      placeholder: Android 12
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false